const products = [
  {
    id: 26,
    name: 'Featured Car 1',
    slug: 't-shirt-with-logo',
    permalink: 'http://localhost:10004/product/t-shirt-with-logo/',
    date_created: '2019-01-16T13:01:55',
    date_created_gmt: '2019-01-16T13:01:55',
    date_modified: '2022-02-14T04:15:25',
    date_modified_gmt: '2022-02-14T04:15:25',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'Woo-tshirt-logo',
    price: '599',
    regular_price: '18',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '0.5',
    dimensions: {
      length: '10',
      width: '12',
      height: '0.5',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 410,
        name: 'Clothing',
        slug: 'clothing',
      },
      {
        id: 412,
        name: 'featured',
        slug: 'featured',
      },
      {
        id: 404,
        name: 'Tshirts',
        slug: 'tshirts',
      },
    ],
    tags: [],
    images: [
      {
        id: 1828,
        date_created: '2022-02-14T03:28:36',
        date_created_gmt: '2022-02-14T03:28:36',
        date_modified: '2022-02-14T03:28:36',
        date_modified_gmt: '2022-02-14T03:28:36',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-1.jpg',
        name: 'car-1',
        alt: '',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'color',
        position: 0,
        visible: true,
        variation: false,
        options: ['Gray'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span>',
    related_ids: [27, 28, 6, 16, 1817],
    meta_data: [
      {
        id: 5309,
        key: 'product_points',
        value: '300',
      },
      {
        id: 5310,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5311,
        key: 'moose',
        value: 'MOOSE IS LOOSE',
      },
      {
        id: 5312,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/26',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 27,
    name: 'Featured Car 2',
    slug: 'beanie-with-logo',
    permalink: 'http://localhost:10004/product/beanie-with-logo/',
    date_created: '2019-01-16T13:01:55',
    date_created_gmt: '2019-01-16T13:01:55',
    date_modified: '2022-02-14T04:16:20',
    date_modified_gmt: '2022-02-14T04:16:20',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'Woo-beanie-logo',
    price: '567',
    regular_price: '20',
    sale_price: '18',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '0.2',
    dimensions: {
      length: '6',
      width: '4',
      height: '1',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 407,
        name: 'Accessories',
        slug: 'accessories',
      },
      {
        id: 412,
        name: 'featured',
        slug: 'featured',
      },
    ],
    tags: [],
    images: [
      {
        id: 1829,
        date_created: '2022-02-14T03:28:37',
        date_created_gmt: '2022-02-14T03:28:37',
        date_modified: '2022-02-14T03:28:37',
        date_modified_gmt: '2022-02-14T03:28:37',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-2.jpg',
        name: 'car-2',
        alt: '',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'color',
        position: 0,
        visible: true,
        variation: false,
        options: ['Red'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span></ins>',
    related_ids: [1817, 26, 10, 13, 1812],
    meta_data: [
      {
        id: 5315,
        key: 'product_points',
        value: '324',
      },
      {
        id: 5316,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5317,
        key: 'moose',
        value: '',
      },
      {
        id: 5318,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/27',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 28,
    name: 'Featured Car 3',
    slug: 'logo-collection',
    permalink: 'http://localhost:10004/product/logo-collection/',
    date_created: '2019-01-16T13:01:55',
    date_created_gmt: '2019-01-16T13:01:55',
    date_modified: '2022-02-14T04:17:48',
    date_modified_gmt: '2022-02-14T04:17:48',
    type: 'grouped',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a grouped product.</p>\n',
    sku: 'logo-collection',
    price: '550',
    regular_price: '',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    dimensions: {
      length: '',
      width: '',
      height: '',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 410,
        name: 'Clothing',
        slug: 'clothing',
      },
    ],
    tags: [],
    images: [
      {
        id: 1842,
        date_created: '2022-02-14T03:28:42',
        date_created_gmt: '2022-02-14T03:28:42',
        date_modified: '2022-02-14T03:28:42',
        date_modified_gmt: '2022-02-14T03:28:42',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-3.jpg',
        name: 'car-15',
        alt: '',
      },
      {
        id: 50,
        date_created: '2019-01-16T13:02:12',
        date_created_gmt: '2019-01-16T13:02:12',
        date_modified: '2019-01-16T13:02:12',
        date_modified_gmt: '2019-01-16T13:02:12',
        src: 'http://localhost:10004/wp-content/uploads/2019/01/beanie-with-logo-1.jpg',
        name: 'beanie-with-logo-1.jpg',
        alt: '',
      },
      {
        id: 49,
        date_created: '2019-01-16T13:02:11',
        date_created_gmt: '2019-01-16T13:02:11',
        date_modified: '2019-01-16T13:02:11',
        date_modified_gmt: '2019-01-16T13:02:11',
        src: 'http://localhost:10004/wp-content/uploads/2019/01/t-shirt-with-logo-1.jpg',
        name: 't-shirt-with-logo-1.jpg',
        alt: '',
      },
      {
        id: 37,
        date_created: '2019-01-16T13:02:01',
        date_created_gmt: '2019-01-16T13:02:01',
        date_modified: '2019-01-16T13:02:01',
        date_modified_gmt: '2019-01-16T13:02:01',
        src: 'http://localhost:10004/wp-content/uploads/2019/01/hoodie-with-logo-2.jpg',
        name: 'hoodie-with-logo-2.jpg',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [8, 9, 10],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span> &ndash; <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>45.00</bdi></span>',
    related_ids: [26],
    meta_data: [
      {
        id: 5321,
        key: 'product_points',
        value: '800',
      },
      {
        id: 5322,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5323,
        key: 'moose',
        value: '',
      },
      {
        id: 5324,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/28',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 1817,
    name: 'Featured Car 3',
    slug: 'wordpress-pennant',
    permalink: 'http://localhost:10004/product/wordpress-pennant/',
    date_created: '2019-01-16T13:01:55',
    date_created_gmt: '2019-01-16T13:01:55',
    date_modified: '2022-02-14T04:18:42',
    date_modified_gmt: '2022-02-14T04:18:42',
    type: 'external',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is an external product.</p>\n',
    sku: 'wp-pennant',
    price: '656',
    regular_price: '11.05',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: 'https://mercantile.wordpress.org/product/wordpress-pennant/',
    button_text: 'Buy on the WordPress swag store!',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    dimensions: {
      length: '',
      width: '',
      height: '',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 411,
        name: 'Decor',
        slug: 'decor',
      },
      {
        id: 412,
        name: 'featured',
        slug: 'featured',
      },
    ],
    tags: [],
    images: [
      {
        id: 1830,
        date_created: '2022-02-14T03:28:37',
        date_created_gmt: '2022-02-14T03:28:37',
        date_modified: '2022-02-14T03:28:37',
        date_modified_gmt: '2022-02-14T03:28:37',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-3.jpg',
        name: 'car-3',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>11.05</bdi></span>',
    related_ids: [26, 27],
    meta_data: [
      {
        id: 5327,
        key: 'product_points',
        value: '200',
      },
      {
        id: 5328,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5329,
        key: 'moose',
        value: '',
      },
      {
        id: 5330,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/1817',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 18,
    name: 'Featured Car 4',
    slug: 'album',
    permalink: 'http://localhost:10004/product/album/',
    date_created: '2019-01-16T13:01:54',
    date_created_gmt: '2019-01-16T13:01:54',
    date_modified: '2022-02-14T04:19:33',
    date_modified_gmt: '2022-02-14T04:19:33',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>\n',
    short_description: '<p>This is a simple, virtual product.</p>\n',
    sku: 'woo-album',
    price: '15',
    regular_price: '15',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: true,
    downloadable: true,
    downloads: [
      {
        id: '356506a5-cc15-41b9-801b-9104dda1702c',
        name: 'Single 1',
        file: 'https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg',
      },
      {
        id: '18e70c59-59f3-43a3-8525-ce1ea0c12943',
        name: 'Single 2',
        file: 'https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/album.jpg',
      },
    ],
    download_limit: 1,
    download_expiry: 1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    dimensions: {
      length: '',
      width: '',
      height: '',
    },
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 409,
        name: 'Music',
        slug: 'music',
      },
    ],
    tags: [],
    images: [
      {
        id: 1831,
        date_created: '2022-02-14T03:28:38',
        date_created_gmt: '2022-02-14T03:28:38',
        date_modified: '2022-02-14T03:28:38',
        date_modified_gmt: '2022-02-14T03:28:38',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-4.jpg',
        name: 'car-4',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>15.00</bdi></span>',
    related_ids: [19],
    meta_data: [
      {
        id: 5333,
        key: 'product_points',
        value: '950',
      },
      {
        id: 5334,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5335,
        key: 'moose',
        value: '',
      },
      {
        id: 5336,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/18',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 19,
    name: 'Sports Car 1',
    slug: 'single',
    permalink: 'http://localhost:10004/product/single/',
    date_created: '2019-01-16T13:01:54',
    date_created_gmt: '2019-01-16T13:01:54',
    date_modified: '2022-02-14T04:20:47',
    date_modified_gmt: '2022-02-14T04:20:47',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>\n',
    short_description: '<p>This is a simple, virtual product.</p>\n',
    sku: 'woo-single',
    price: '2',
    regular_price: '3',
    sale_price: '2',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: true,
    downloadable: true,
    downloads: [
      {
        id: 'a0fdda89-5f0e-440d-93f5-188e12c910d1',
        name: 'Single',
        file: 'https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg',
      },
    ],
    download_limit: 1,
    download_expiry: 1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    dimensions: {
      length: '',
      width: '',
      height: '',
    },
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 409,
        name: 'Music',
        slug: 'music',
      },
    ],
    tags: [],
    images: [
      {
        id: 1832,
        date_created: '2022-02-14T03:28:38',
        date_created_gmt: '2022-02-14T03:28:38',
        date_modified: '2022-02-14T03:28:38',
        date_modified_gmt: '2022-02-14T03:28:38',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-5.jpg',
        name: 'car-5',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>3.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>2.00</bdi></span></ins>',
    related_ids: [18],
    meta_data: [
      {
        id: 5339,
        key: 'product_points',
        value: '555',
      },
      {
        id: 5340,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5341,
        key: 'moose',
        value: '',
      },
      {
        id: 5342,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/19',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 13,
    name: 'Sports Car 2',
    slug: 'sunglasses',
    permalink: 'http://localhost:10004/product/sunglasses/',
    date_created: '2019-01-16T13:01:53',
    date_created_gmt: '2019-01-16T13:01:53',
    date_modified: '2022-02-14T04:21:41',
    date_modified_gmt: '2022-02-14T04:21:41',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'woo-sunglasses',
    price: '90',
    regular_price: '90',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '0.2',
    dimensions: {
      length: '4',
      width: '1.4',
      height: '1',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 407,
        name: 'Accessories',
        slug: 'accessories',
      },
    ],
    tags: [],
    images: [
      {
        id: 1833,
        date_created: '2022-02-14T03:28:39',
        date_created_gmt: '2022-02-14T03:28:39',
        date_modified: '2022-02-14T03:28:39',
        date_modified_gmt: '2022-02-14T03:28:39',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-6.jpg',
        name: '3D Sport Car Vehicle Transportation Illustration Concept',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>90.00</bdi></span>',
    related_ids: [11, 10, 1812, 27],
    meta_data: [
      {
        id: 5345,
        key: 'product_points',
        value: '750',
      },
      {
        id: 5346,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5347,
        key: 'moose',
        value: '',
      },
      {
        id: 5348,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/13',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 15,
    name: 'Sports Car 3',
    slug: 'hoodie-with-zipper',
    permalink: 'http://localhost:10004/product/hoodie-with-zipper/',
    date_created: '2019-01-16T13:01:53',
    date_created_gmt: '2019-01-16T13:01:53',
    date_modified: '2022-02-14T04:22:52',
    date_modified_gmt: '2022-02-14T04:22:52',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'woo-hoodie-with-zipper',
    price: '45',
    regular_price: '45',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '2',
    dimensions: {
      length: '8',
      width: '6',
      height: '2',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 405,
        name: 'Hoodies',
        slug: 'hoodies',
      },
    ],
    tags: [],
    images: [
      {
        id: 1834,
        date_created: '2022-02-14T03:28:39',
        date_created_gmt: '2022-02-14T03:28:39',
        date_modified: '2022-02-14T03:28:39',
        date_modified_gmt: '2022-02-14T03:28:39',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-7.jpg',
        name: 'car-7',
        alt: '',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>45.00</bdi></span>',
    related_ids: [7, 8],
    meta_data: [
      {
        id: 5351,
        key: 'product_points',
        value: '1200',
      },
      {
        id: 5352,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5353,
        key: 'moose',
        value: '',
      },
      {
        id: 5354,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/15',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 16,
    name: 'Sports Car 4',
    slug: 'long-sleeve-tee',
    permalink: 'http://localhost:10004/product/long-sleeve-tee/',
    date_created: '2019-01-16T13:01:53',
    date_created_gmt: '2019-01-16T13:01:53',
    date_modified: '2022-02-14T04:23:55',
    date_modified_gmt: '2022-02-14T04:23:55',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'woo-long-sleeve-tee',
    price: '25',
    regular_price: '25',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '1',
    dimensions: {
      length: '7',
      width: '5',
      height: '1',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 404,
        name: 'Tshirts',
        slug: 'tshirts',
      },
    ],
    tags: [],
    images: [
      {
        id: 1835,
        date_created: '2022-02-14T03:28:40',
        date_created_gmt: '2022-02-14T03:28:40',
        date_modified: '2022-02-14T03:28:40',
        date_modified_gmt: '2022-02-14T03:28:40',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-8.jpg',
        name: 'car-8',
        alt: '',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'color',
        position: 0,
        visible: true,
        variation: false,
        options: ['Green'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>25.00</bdi></span>',
    related_ids: [6, 1814, 26, 9],
    meta_data: [
      {
        id: 5357,
        key: 'product_points',
        value: '1050',
      },
      {
        id: 5358,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5359,
        key: 'moose',
        value: '',
      },
      {
        id: 5360,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/16',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
  {
    id: 1812,
    name: 'Street Car 1',
    slug: 'cap',
    permalink: 'http://localhost:10004/product/cap/',
    date_created: '2019-01-16T13:01:53',
    date_created_gmt: '2019-01-16T13:01:53',
    date_modified: '2022-02-14T04:25:03',
    date_modified_gmt: '2022-02-14T04:25:03',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description:
      '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n',
    short_description: '<p>This is a simple product.</p>\n',
    sku: 'woo-cap',
    price: '16',
    regular_price: '18',
    sale_price: '16',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '0.6',
    dimensions: {
      length: '8',
      width: '6.5',
      height: '4',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 407,
        name: 'Accessories',
        slug: 'accessories',
      },
    ],
    tags: [],
    images: [
      {
        id: 1836,
        date_created: '2022-02-14T03:28:40',
        date_created_gmt: '2022-02-14T03:28:40',
        date_modified: '2022-02-14T03:28:40',
        date_modified_gmt: '2022-02-14T03:28:40',
        src: 'http://localhost:10004/wp-content/uploads/2022/02/car-9.jpg',
        name: 'car-9',
        alt: '',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'color',
        position: 0,
        visible: true,
        variation: false,
        options: ['Yellow'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>16.00</bdi></span></ins>',
    related_ids: [10, 27, 11, 13],
    meta_data: [
      {
        id: 5363,
        key: 'product_points',
        value: '250',
      },
      {
        id: 5364,
        key: '_product_points',
        value: 'field_6025f26db4fb2',
      },
      {
        id: 5365,
        key: 'moose',
        value: '',
      },
      {
        id: 5366,
        key: '_moose',
        value: 'field_62033f602d34e',
      },
    ],
    stock_status: 'instock',
    _links: {
      self: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products/1812',
        },
      ],
      collection: [
        {
          href: 'http://localhost:10004/wp-json/wc/v3/products',
        },
      ],
    },
  },
];

export default products;
